### ISSUE TITLE
脚本对已经声明了 exported 的组件重复添加

### ISSUE THREAD

**Issue by mikeFei1000** [xiachufang/manifest-exported-plugin#1]

**Comment by Petterpx** [comment]
> _No description provided._

收到，晚点我看看。

**Comment by Petterpx** [comment]
> _No description provided._

感谢反馈，晚点我看看。

**Comment by Petterpx** [comment]
> _No description provided._

你好，这边测试未复现此问题，你可以在主model-build-exported文件下查看outManifestLog.md文件查看运行日志。如果还存在问题，可以附带你的agb与gradle版本，我再尝试下。
